name: "Docker Build & Push Action"
description: "Builds a Docker image and pushes to a private registry with support for multiple tags"
author: "Sean Smith"
inputs:
  image:
    description: "Name of the Docker image"
    required: true
  registry:
    description: "Target Docker registry"
    required: true

  username:
    description: "Docker registry username"
    required: false
  password:
    description: "Docker registry password"
    required: false
outputs:
  targetImageName:
    description: "Name of the Docker image that was pushed"
runs:
  using: "node14"
  main: "dist/index.js"
